# Generated by Django 4.2.30 on 2026-04-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('total_area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('crop_type', models.CharField(choices=[('tree_crop', 'Tree Crop'), ('spice', 'Spice'), ('plantation', 'Plantation')], max_length=50)),
                ('planting_density_per_hectare', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(db_index=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('work_detail', models.CharField(blank=True, max_length=255)),
                ('male_labour_count', models.IntegerField(default=0)),
                ('female_labour_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('synced', 'Synced')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('client_sync_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core_app.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core_app.crop')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('daily_rate_rs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('contract', 'Contract')], default='temporary', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('left', 'Left')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Nursery', 'Nursery'), ('Field', 'Field'), ('Tree', 'Tree Management'), ('Processing', 'Processing'), ('Misc', 'Miscellaneous')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkLogAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('wage_earned_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.dailyworklog')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.worker')),
            ],
            options={
                'unique_together': {('work_log', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core_app.worktype'),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='workers',
            field=models.ManyToManyField(related_name='work_logs', through='core_app.WorkLogAttendance', to='core_app.worker'),
        ),
        migrations.CreateModel(
            name='BlockCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rows', models.IntegerField(default=6)),
                ('trees_per_row', models.JSONField(default=dict)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_season', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='core_app.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core_app.crop')),
            ],
            options={
                'ordering': ['block', 'crop'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['log_date', 'block'], name='core_app_da_log_dat_290214_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['crop'], name='core_app_da_crop_id_0f48cb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyworklog',
            index=models.Index(fields=['status'], name='core_app_da_status_d80a93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockcrop',
            unique_together={('block', 'crop')},
        ),
    ]
