# Generated by Django 4.2.30 on 2026-04-07 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworklog',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='Hours worked per labourer', max_digits=4),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core_app.crop')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('crop', 'name', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='core_app.season'),
        ),
    ]
