# Generated by Django 4.2.30 on 2026-04-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0003_inventoryitem_weatherrecord_inventorytransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={},
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('present_morning', models.BooleanField(default=False)),
                ('present_afternoon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.worker')),
            ],
            options={
                'ordering': ['-date', 'worker'],
                'unique_together': {('date', 'worker')},
            },
        ),
    ]
