# Generated by Django 4.2.30 on 2026-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_weatherrecord_options_dailyattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'sub_category', 'name']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('BaseMaterial', 'Base Material'), ('Solutions', 'Solutions'), ('Tools', 'Tools'), ('Consumables', 'Consumables'), ('Produce', 'Produce'), ('Expense', 'Expense')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('GMS', 'Grams'), ('KG', 'Kilograms'), ('LTR', 'Liters'), ('MT', 'Metric Tons'), ('NOS', 'Numbers')], default='NOS', max_length=20),
        ),
    ]
